// country.ts

/*
 * Currency/country database, including country codes, ISO 4217 currency information
 *
 * Original source: https://datahub.io/core/country-codes
 * Licensed under: https://opendatacommons.org/licenses/pddl/
 */

export interface Country {
  name: string;
  alpha2: string;
  alpha3: string;
  numeric: string;
  currencyAlphabeticCode: string;
  currencyNumericCode: string;
  currencyCountryName: string;
  currencyMinorUnit: string;
  currencyName: string;
}

const countryDatabase: Country[] = [
  {
    name: 'Taiwan',
    alpha2: 'TW',
    alpha3: 'TWN',
    numeric: '158',
    currencyCountryName: 'TAIWAN (PROVINCE OF CHINA)',
    currencyName: 'New Taiwan Dollar',
    currencyAlphabeticCode: 'TWD',
    currencyNumericCode: '901',
    currencyMinorUnit: '2'
  },
  {
    name: 'Afghanistan',
    alpha2: 'AF',
    alpha3: 'AFG',
    numeric: '004',
    currencyAlphabeticCode: 'AFN',
    currencyCountryName: 'AFGHANISTAN',
    currencyMinorUnit: '2',
    currencyName: 'Afghani',
    currencyNumericCode: '971'
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    numeric: '008',
    currencyAlphabeticCode: 'ALL',
    currencyCountryName: 'ALBANIA',
    currencyMinorUnit: '2',
    currencyName: 'Lek',
    currencyNumericCode: '008'
  },
  {
    name: 'Algeria',
    alpha2: 'DZ',
    alpha3: 'DZA',
    numeric: '012',
    currencyAlphabeticCode: 'DZD',
    currencyCountryName: 'ALGERIA',
    currencyMinorUnit: '2',
    currencyName: 'Algerian Dinar',
    currencyNumericCode: '012'
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    numeric: '016',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'AMERICAN SAMOA',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    numeric: '020',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'ANDORRA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    numeric: '024',
    currencyAlphabeticCode: 'AOA',
    currencyCountryName: 'ANGOLA',
    currencyMinorUnit: '2',
    currencyName: 'Kwanza',
    currencyNumericCode: '973'
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    numeric: '660',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'ANGUILLA',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'Antigua & Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    numeric: '028',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'ANTIGUA AND BARBUDA',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha3: 'ARG',
    numeric: '032',
    currencyAlphabeticCode: 'ARS',
    currencyCountryName: 'ARGENTINA',
    currencyMinorUnit: '2',
    currencyName: 'Argentine Peso',
    currencyNumericCode: '032'
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    numeric: '051',
    currencyAlphabeticCode: 'AMD',
    currencyCountryName: 'ARMENIA',
    currencyMinorUnit: '2',
    currencyName: 'Armenian Dram',
    currencyNumericCode: '051'
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    numeric: '533',
    currencyAlphabeticCode: 'AWG',
    currencyCountryName: 'ARUBA',
    currencyMinorUnit: '2',
    currencyName: 'Aruban Florin',
    currencyNumericCode: '533'
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    numeric: '036',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'AUSTRALIA',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    numeric: '040',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'AUSTRIA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    numeric: '031',
    currencyAlphabeticCode: 'AZN',
    currencyCountryName: 'AZERBAIJAN',
    currencyMinorUnit: '2',
    currencyName: 'Azerbaijan Manat',
    currencyNumericCode: '944'
  },
  {
    name: 'Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    numeric: '044',
    currencyAlphabeticCode: 'BSD',
    currencyCountryName: 'BAHAMAS',
    currencyMinorUnit: '2',
    currencyName: 'Bahamian Dollar',
    currencyNumericCode: '044'
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    numeric: '048',
    currencyAlphabeticCode: 'BHD',
    currencyCountryName: 'BAHRAIN',
    currencyMinorUnit: '3',
    currencyName: 'Bahraini Dinar',
    currencyNumericCode: '048'
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    alpha3: 'BGD',
    numeric: '050',
    currencyAlphabeticCode: 'BDT',
    currencyCountryName: 'BANGLADESH',
    currencyMinorUnit: '2',
    currencyName: 'Taka',
    currencyNumericCode: '050'
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    numeric: '052',
    currencyAlphabeticCode: 'BBD',
    currencyCountryName: 'BARBADOS',
    currencyMinorUnit: '2',
    currencyName: 'Barbados Dollar',
    currencyNumericCode: '052'
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    numeric: '112',
    currencyAlphabeticCode: 'BYN',
    currencyCountryName: 'BELARUS',
    currencyMinorUnit: '2',
    currencyName: 'Belarusian Ruble',
    currencyNumericCode: '933'
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    numeric: '056',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'BELGIUM',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    numeric: '084',
    currencyAlphabeticCode: 'BZD',
    currencyCountryName: 'BELIZE',
    currencyMinorUnit: '2',
    currencyName: 'Belize Dollar',
    currencyNumericCode: '084'
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    numeric: '204',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: 'BENIN',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    alpha3: 'BMU',
    numeric: '060',
    currencyAlphabeticCode: 'BMD',
    currencyCountryName: 'BERMUDA',
    currencyMinorUnit: '2',
    currencyName: 'Bermudian Dollar',
    currencyNumericCode: '060'
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    numeric: '064',
    currencyAlphabeticCode: 'INR,BTN',
    currencyCountryName: 'BHUTAN',
    currencyMinorUnit: '2,2',
    currencyName: 'Indian Rupee,Ngultrum',
    currencyNumericCode: '356,064'
  },
  {
    name: 'Bolivia',
    alpha2: 'BO',
    alpha3: 'BOL',
    numeric: '068',
    currencyAlphabeticCode: 'BOB',
    currencyCountryName: 'BOLIVIA (PLURINATIONAL STATE OF)',
    currencyMinorUnit: '2',
    currencyName: 'Boliviano',
    currencyNumericCode: '068'
  },
  {
    name: 'Caribbean Netherlands',
    alpha2: 'BQ',
    alpha3: 'BES',
    numeric: '535',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'BONAIRE, SINT EUSTATIUS AND SABA',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Bosnia',
    alpha2: 'BA',
    alpha3: 'BIH',
    numeric: '070',
    currencyAlphabeticCode: 'BAM',
    currencyCountryName: 'BOSNIA AND HERZEGOVINA',
    currencyMinorUnit: '2',
    currencyName: 'Convertible Mark',
    currencyNumericCode: '977'
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    numeric: '072',
    currencyAlphabeticCode: 'BWP',
    currencyCountryName: 'BOTSWANA',
    currencyMinorUnit: '2',
    currencyName: 'Pula',
    currencyNumericCode: '072'
  },
  {
    name: 'Bouvet Island',
    alpha2: 'BV',
    alpha3: 'BVT',
    numeric: '074',
    currencyAlphabeticCode: 'NOK',
    currencyCountryName: 'BOUVET ISLAND',
    currencyMinorUnit: '2',
    currencyName: 'Norwegian Krone',
    currencyNumericCode: '578'
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    numeric: '076',
    currencyAlphabeticCode: 'BRL',
    currencyCountryName: 'BRAZIL',
    currencyMinorUnit: '2',
    currencyName: 'Brazilian Real',
    currencyNumericCode: '986'
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2: 'IO',
    alpha3: 'IOT',
    numeric: '086',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'BRITISH INDIAN OCEAN TERRITORY',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'British Virgin Islands',
    alpha2: 'VG',
    alpha3: 'VGB',
    numeric: '092',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'VIRGIN ISLANDS (BRITISH)',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Brunei',
    alpha2: 'BN',
    alpha3: 'BRN',
    numeric: '096',
    currencyAlphabeticCode: 'BND',
    currencyCountryName: 'BRUNEI DARUSSALAM',
    currencyMinorUnit: '2',
    currencyName: 'Brunei Dollar',
    currencyNumericCode: '096'
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    numeric: '100',
    currencyAlphabeticCode: 'BGN',
    currencyCountryName: 'BULGARIA',
    currencyMinorUnit: '2',
    currencyName: 'Bulgarian Lev',
    currencyNumericCode: '975'
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    numeric: '854',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: 'BURKINA FASO',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    numeric: '108',
    currencyAlphabeticCode: 'BIF',
    currencyCountryName: 'BURUNDI',
    currencyMinorUnit: '0',
    currencyName: 'Burundi Franc',
    currencyNumericCode: '108'
  },
  {
    name: 'Cape Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    numeric: '132',
    currencyAlphabeticCode: 'CVE',
    currencyCountryName: 'CABO VERDE',
    currencyMinorUnit: '2',
    currencyName: 'Cabo Verde Escudo',
    currencyNumericCode: '132'
  },
  {
    name: 'Cambodia',
    alpha2: 'KH',
    alpha3: 'KHM',
    numeric: '116',
    currencyAlphabeticCode: 'KHR',
    currencyCountryName: 'CAMBODIA',
    currencyMinorUnit: '2',
    currencyName: 'Riel',
    currencyNumericCode: '116'
  },
  {
    name: 'Cameroon',
    alpha2: 'CM',
    alpha3: 'CMR',
    numeric: '120',
    currencyAlphabeticCode: 'XAF',
    currencyCountryName: 'CAMEROON',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BEAC',
    currencyNumericCode: '950'
  },
  {
    name: 'Canada',
    alpha2: 'CA',
    alpha3: 'CAN',
    numeric: '124',
    currencyAlphabeticCode: 'CAD',
    currencyCountryName: 'CANADA',
    currencyMinorUnit: '2',
    currencyName: 'Canadian Dollar',
    currencyNumericCode: '124'
  },
  {
    name: 'Cayman Islands',
    alpha2: 'KY',
    alpha3: 'CYM',
    numeric: '136',
    currencyAlphabeticCode: 'KYD',
    currencyCountryName: 'CAYMAN ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'Cayman Islands Dollar',
    currencyNumericCode: '136'
  },
  {
    name: 'Central African Republic',
    alpha2: 'CF',
    alpha3: 'CAF',
    numeric: '140',
    currencyAlphabeticCode: 'XAF',
    currencyCountryName: 'CENTRAL AFRICAN REPUBLIC',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BEAC',
    currencyNumericCode: '950'
  },
  {
    name: 'Chad',
    alpha2: 'TD',
    alpha3: 'TCD',
    numeric: '148',
    currencyAlphabeticCode: 'XAF',
    currencyCountryName: 'CHAD',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BEAC',
    currencyNumericCode: '950'
  },
  {
    name: 'Chile',
    alpha2: 'CL',
    alpha3: 'CHL',
    numeric: '152',
    currencyAlphabeticCode: 'CLP',
    currencyCountryName: 'CHILE',
    currencyMinorUnit: '0',
    currencyName: 'Chilean Peso',
    currencyNumericCode: '152'
  },
  {
    name: 'China',
    alpha2: 'CN',
    alpha3: 'CHN',
    numeric: '156',
    currencyAlphabeticCode: 'CNY',
    currencyCountryName: 'CHINA',
    currencyMinorUnit: '2',
    currencyName: 'Yuan Renminbi',
    currencyNumericCode: '156'
  },
  {
    name: 'Hong Kong',
    alpha2: 'HK',
    alpha3: 'HKG',
    numeric: '344',
    currencyAlphabeticCode: 'HKD',
    currencyCountryName: 'HONG KONG',
    currencyMinorUnit: '2',
    currencyName: 'Hong Kong Dollar',
    currencyNumericCode: '344'
  },
  {
    name: 'Macau',
    alpha2: 'MO',
    alpha3: 'MAC',
    numeric: '446',
    currencyAlphabeticCode: 'MOP',
    currencyCountryName: 'MACAO',
    currencyMinorUnit: '2',
    currencyName: 'Pataca',
    currencyNumericCode: '446'
  },
  {
    name: 'Christmas Island',
    alpha2: 'CX',
    alpha3: 'CXR',
    numeric: '162',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'CHRISTMAS ISLAND',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2: 'CC',
    alpha3: 'CCK',
    numeric: '166',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'COCOS (KEELING) ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Colombia',
    alpha2: 'CO',
    alpha3: 'COL',
    numeric: '170',
    currencyAlphabeticCode: 'COP',
    currencyCountryName: 'COLOMBIA',
    currencyMinorUnit: '2',
    currencyName: 'Colombian Peso',
    currencyNumericCode: '170'
  },
  {
    name: 'Comoros',
    alpha2: 'KM',
    alpha3: 'COM',
    numeric: '174',
    currencyAlphabeticCode: 'KMF',
    currencyCountryName: 'COMOROS',
    currencyMinorUnit: '0',
    currencyName: 'Comorian Franc',
    currencyNumericCode: '174'
  },
  {
    name: 'Congo - Brazzaville',
    alpha2: 'CG',
    alpha3: 'COG',
    numeric: '178',
    currencyAlphabeticCode: 'XAF',
    currencyCountryName: 'CONGO',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BEAC',
    currencyNumericCode: '950'
  },
  {
    name: 'Cook Islands',
    alpha2: 'CK',
    alpha3: 'COK',
    numeric: '184',
    currencyAlphabeticCode: 'NZD',
    currencyCountryName: 'COOK ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'New Zealand Dollar',
    currencyNumericCode: '554'
  },
  {
    name: 'Costa Rica',
    alpha2: 'CR',
    alpha3: 'CRI',
    numeric: '188',
    currencyAlphabeticCode: 'CRC',
    currencyCountryName: 'COSTA RICA',
    currencyMinorUnit: '2',
    currencyName: 'Costa Rican Colon',
    currencyNumericCode: '188'
  },
  {
    name: 'Croatia',
    alpha2: 'HR',
    alpha3: 'HRV',
    numeric: '191',
    currencyAlphabeticCode: 'HRK',
    currencyCountryName: 'CROATIA',
    currencyMinorUnit: '2',
    currencyName: 'Kuna',
    currencyNumericCode: '191'
  },
  {
    name: 'Cuba',
    alpha2: 'CU',
    alpha3: 'CUB',
    numeric: '192',
    currencyAlphabeticCode: 'CUP,CUC',
    currencyCountryName: 'CUBA',
    currencyMinorUnit: '2,2',
    currencyName: 'Cuban Peso,Peso Convertible',
    currencyNumericCode: '192,931'
  },
  {
    name: 'Cura\u00e7ao',
    alpha2: 'CW',
    alpha3: 'CUW',
    numeric: '531',
    currencyAlphabeticCode: 'ANG',
    currencyCountryName: 'CURA\u00c7AO',
    currencyMinorUnit: '2',
    currencyName: 'Netherlands Antillean Guilder',
    currencyNumericCode: '532'
  },
  {
    name: 'Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    numeric: '196',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'CYPRUS',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Czechia',
    alpha2: 'CZ',
    alpha3: 'CZE',
    numeric: '203',
    currencyAlphabeticCode: 'CZK',
    currencyCountryName: 'CZECHIA',
    currencyMinorUnit: '2',
    currencyName: 'Czech Koruna',
    currencyNumericCode: '203'
  },
  {
    name: 'C\u00f4te d\u2019Ivoire',
    alpha2: 'CI',
    alpha3: 'CIV',
    numeric: '384',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: "C\u00d4TE D'IVOIRE",
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'North Korea',
    alpha2: 'KP',
    alpha3: 'PRK',
    numeric: '408',
    currencyAlphabeticCode: 'KPW',
    currencyCountryName: 'KOREA (THE DEMOCRATIC PEOPLE\u2019S REPUBLIC OF)',
    currencyMinorUnit: '2',
    currencyName: 'North Korean Won',
    currencyNumericCode: '408'
  },
  {
    name: 'Congo - Kinshasa',
    alpha2: 'CD',
    alpha3: 'COD',
    numeric: '180',
    currencyAlphabeticCode: 'CDF',
    currencyCountryName: 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
    currencyMinorUnit: '2',
    currencyName: 'Congolese Franc',
    currencyNumericCode: '976'
  },
  {
    name: 'Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    numeric: '208',
    currencyAlphabeticCode: 'DKK',
    currencyCountryName: 'DENMARK',
    currencyMinorUnit: '2',
    currencyName: 'Danish Krone',
    currencyNumericCode: '208'
  },
  {
    name: 'Djibouti',
    alpha2: 'DJ',
    alpha3: 'DJI',
    numeric: '262',
    currencyAlphabeticCode: 'DJF',
    currencyCountryName: 'DJIBOUTI',
    currencyMinorUnit: '0',
    currencyName: 'Djibouti Franc',
    currencyNumericCode: '262'
  },
  {
    name: 'Dominica',
    alpha2: 'DM',
    alpha3: 'DMA',
    numeric: '212',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'DOMINICA',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'Dominican Republic',
    alpha2: 'DO',
    alpha3: 'DOM',
    numeric: '214',
    currencyAlphabeticCode: 'DOP',
    currencyCountryName: 'DOMINICAN REPUBLIC',
    currencyMinorUnit: '2',
    currencyName: 'Dominican Peso',
    currencyNumericCode: '214'
  },
  {
    name: 'Ecuador',
    alpha2: 'EC',
    alpha3: 'ECU',
    numeric: '218',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'ECUADOR',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Egypt',
    alpha2: 'EG',
    alpha3: 'EGY',
    numeric: '818',
    currencyAlphabeticCode: 'EGP',
    currencyCountryName: 'EGYPT',
    currencyMinorUnit: '2',
    currencyName: 'Egyptian Pound',
    currencyNumericCode: '818'
  },
  {
    name: 'El Salvador',
    alpha2: 'SV',
    alpha3: 'SLV',
    numeric: '222',
    currencyAlphabeticCode: 'SVC,USD',
    currencyCountryName: 'EL SALVADOR',
    currencyMinorUnit: '2,2',
    currencyName: 'El Salvador Colon,US Dollar',
    currencyNumericCode: '222,840'
  },
  {
    name: 'Equatorial Guinea',
    alpha2: 'GQ',
    alpha3: 'GNQ',
    numeric: '226',
    currencyAlphabeticCode: 'XAF',
    currencyCountryName: 'EQUATORIAL GUINEA',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BEAC',
    currencyNumericCode: '950'
  },
  {
    name: 'Eritrea',
    alpha2: 'ER',
    alpha3: 'ERI',
    numeric: '232',
    currencyAlphabeticCode: 'ERN',
    currencyCountryName: 'ERITREA',
    currencyMinorUnit: '2',
    currencyName: 'Nakfa',
    currencyNumericCode: '232'
  },
  {
    name: 'Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    numeric: '233',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'ESTONIA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    numeric: '231',
    currencyAlphabeticCode: 'ETB',
    currencyCountryName: 'ETHIOPIA',
    currencyMinorUnit: '2',
    currencyName: 'Ethiopian Birr',
    currencyNumericCode: '230'
  },
  {
    name: 'Faroe Islands',
    alpha2: 'FO',
    alpha3: 'FRO',
    numeric: '234',
    currencyAlphabeticCode: 'DKK',
    currencyCountryName: 'FAROE ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'Danish Krone',
    currencyNumericCode: '208'
  },
  {
    name: 'Fiji',
    alpha2: 'FJ',
    alpha3: 'FJI',
    numeric: '242',
    currencyAlphabeticCode: 'FJD',
    currencyCountryName: 'FIJI',
    currencyMinorUnit: '2',
    currencyName: 'Fiji Dollar',
    currencyNumericCode: '242'
  },
  {
    name: 'Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    numeric: '246',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'FINLAND',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'France',
    alpha2: 'FR',
    alpha3: 'FRA',
    numeric: '250',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'FRANCE',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'French Guiana',
    alpha2: 'GF',
    alpha3: 'GUF',
    numeric: '254',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'FRENCH GUIANA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'French Polynesia',
    alpha2: 'PF',
    alpha3: 'PYF',
    numeric: '258',
    currencyAlphabeticCode: 'XPF',
    currencyCountryName: 'FRENCH POLYNESIA',
    currencyMinorUnit: '0',
    currencyName: 'CFP Franc',
    currencyNumericCode: '953'
  },
  {
    name: 'French Southern Territories',
    alpha2: 'TF',
    alpha3: 'ATF',
    numeric: '260',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'FRENCH SOUTHERN TERRITORIES',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Gabon',
    alpha2: 'GA',
    alpha3: 'GAB',
    numeric: '266',
    currencyAlphabeticCode: 'XAF',
    currencyCountryName: 'GABON',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BEAC',
    currencyNumericCode: '950'
  },
  {
    name: 'Gambia',
    alpha2: 'GM',
    alpha3: 'GMB',
    numeric: '270',
    currencyAlphabeticCode: 'GMD',
    currencyCountryName: 'GAMBIA',
    currencyMinorUnit: '2',
    currencyName: 'Dalasi',
    currencyNumericCode: '270'
  },
  {
    name: 'Georgia',
    alpha2: 'GE',
    alpha3: 'GEO',
    numeric: '268',
    currencyAlphabeticCode: 'GEL',
    currencyCountryName: 'GEORGIA',
    currencyMinorUnit: '2',
    currencyName: 'Lari',
    currencyNumericCode: '981'
  },
  {
    name: 'Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    numeric: '276',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'GERMANY',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Ghana',
    alpha2: 'GH',
    alpha3: 'GHA',
    numeric: '288',
    currencyAlphabeticCode: 'GHS',
    currencyCountryName: 'GHANA',
    currencyMinorUnit: '2',
    currencyName: 'Ghana Cedi',
    currencyNumericCode: '936'
  },
  {
    name: 'Gibraltar',
    alpha2: 'GI',
    alpha3: 'GIB',
    numeric: '292',
    currencyAlphabeticCode: 'GIP',
    currencyCountryName: 'GIBRALTAR',
    currencyMinorUnit: '2',
    currencyName: 'Gibraltar Pound',
    currencyNumericCode: '292'
  },
  {
    name: 'Greece',
    alpha2: 'GR',
    alpha3: 'GRC',
    numeric: '300',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'GREECE',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Greenland',
    alpha2: 'GL',
    alpha3: 'GRL',
    numeric: '304',
    currencyAlphabeticCode: 'DKK',
    currencyCountryName: 'GREENLAND',
    currencyMinorUnit: '2',
    currencyName: 'Danish Krone',
    currencyNumericCode: '208'
  },
  {
    name: 'Grenada',
    alpha2: 'GD',
    alpha3: 'GRD',
    numeric: '308',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'GRENADA',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'Guadeloupe',
    alpha2: 'GP',
    alpha3: 'GLP',
    numeric: '312',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'GUADELOUPE',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Guam',
    alpha2: 'GU',
    alpha3: 'GUM',
    numeric: '316',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'GUAM',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Guatemala',
    alpha2: 'GT',
    alpha3: 'GTM',
    numeric: '320',
    currencyAlphabeticCode: 'GTQ',
    currencyCountryName: 'GUATEMALA',
    currencyMinorUnit: '2',
    currencyName: 'Quetzal',
    currencyNumericCode: '320'
  },
  {
    name: 'Guernsey',
    alpha2: 'GG',
    alpha3: 'GGY',
    numeric: '831',
    currencyAlphabeticCode: 'GBP',
    currencyCountryName: 'GUERNSEY',
    currencyMinorUnit: '2',
    currencyName: 'Pound Sterling',
    currencyNumericCode: '826'
  },
  {
    name: 'Guinea',
    alpha2: 'GN',
    alpha3: 'GIN',
    numeric: '324',
    currencyAlphabeticCode: 'GNF',
    currencyCountryName: 'GUINEA',
    currencyMinorUnit: '0',
    currencyName: 'Guinean Franc',
    currencyNumericCode: '324'
  },
  {
    name: 'Guinea-Bissau',
    alpha2: 'GW',
    alpha3: 'GNB',
    numeric: '624',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: 'GUINEA-BISSAU',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'Guyana',
    alpha2: 'GY',
    alpha3: 'GUY',
    numeric: '328',
    currencyAlphabeticCode: 'GYD',
    currencyCountryName: 'GUYANA',
    currencyMinorUnit: '2',
    currencyName: 'Guyana Dollar',
    currencyNumericCode: '328'
  },
  {
    name: 'Haiti',
    alpha2: 'HT',
    alpha3: 'HTI',
    numeric: '332',
    currencyAlphabeticCode: 'HTG,USD',
    currencyCountryName: 'HAITI',
    currencyMinorUnit: '2,2',
    currencyName: 'Gourde,US Dollar',
    currencyNumericCode: '332,840'
  },
  {
    name: 'Heard & McDonald Islands',
    alpha2: 'HM',
    alpha3: 'HMD',
    numeric: '334',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'HEARD ISLAND AND MCDONALD ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Vatican City',
    alpha2: 'VA',
    alpha3: 'VAT',
    numeric: '336',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'HOLY SEE',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Honduras',
    alpha2: 'HN',
    alpha3: 'HND',
    numeric: '340',
    currencyAlphabeticCode: 'HNL',
    currencyCountryName: 'HONDURAS',
    currencyMinorUnit: '2',
    currencyName: 'Lempira',
    currencyNumericCode: '340'
  },
  {
    name: 'Hungary',
    alpha2: 'HU',
    alpha3: 'HUN',
    numeric: '348',
    currencyAlphabeticCode: 'HUF',
    currencyCountryName: 'HUNGARY',
    currencyMinorUnit: '2',
    currencyName: 'Forint',
    currencyNumericCode: '348'
  },
  {
    name: 'Iceland',
    alpha2: 'IS',
    alpha3: 'ISL',
    numeric: '352',
    currencyAlphabeticCode: 'ISK',
    currencyCountryName: 'ICELAND',
    currencyMinorUnit: '0',
    currencyName: 'Iceland Krona',
    currencyNumericCode: '352'
  },
  {
    name: 'India',
    alpha2: 'IN',
    alpha3: 'IND',
    numeric: '356',
    currencyAlphabeticCode: 'INR',
    currencyCountryName: 'INDIA',
    currencyMinorUnit: '2',
    currencyName: 'Indian Rupee',
    currencyNumericCode: '356'
  },
  {
    name: 'Indonesia',
    alpha2: 'ID',
    alpha3: 'IDN',
    numeric: '360',
    currencyAlphabeticCode: 'IDR',
    currencyCountryName: 'INDONESIA',
    currencyMinorUnit: '2',
    currencyName: 'Rupiah',
    currencyNumericCode: '360'
  },
  {
    name: 'Iran',
    alpha2: 'IR',
    alpha3: 'IRN',
    numeric: '364',
    currencyAlphabeticCode: 'IRR',
    currencyCountryName: 'IRAN (ISLAMIC REPUBLIC OF)',
    currencyMinorUnit: '2',
    currencyName: 'Iranian Rial',
    currencyNumericCode: '364'
  },
  {
    name: 'Iraq',
    alpha2: 'IQ',
    alpha3: 'IRQ',
    numeric: '368',
    currencyAlphabeticCode: 'IQD',
    currencyCountryName: 'IRAQ',
    currencyMinorUnit: '3',
    currencyName: 'Iraqi Dinar',
    currencyNumericCode: '368'
  },
  {
    name: 'Ireland',
    alpha2: 'IE',
    alpha3: 'IRL',
    numeric: '372',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'IRELAND',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Isle of Man',
    alpha2: 'IM',
    alpha3: 'IMN',
    numeric: '833',
    currencyAlphabeticCode: 'GBP',
    currencyCountryName: 'ISLE OF MAN',
    currencyMinorUnit: '2',
    currencyName: 'Pound Sterling',
    currencyNumericCode: '826'
  },
  {
    name: 'Israel',
    alpha2: 'IL',
    alpha3: 'ISR',
    numeric: '376',
    currencyAlphabeticCode: 'ILS',
    currencyCountryName: 'ISRAEL',
    currencyMinorUnit: '2',
    currencyName: 'New Israeli Sheqel',
    currencyNumericCode: '376'
  },
  {
    name: 'Italy',
    alpha2: 'IT',
    alpha3: 'ITA',
    numeric: '380',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'ITALY',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Jamaica',
    alpha2: 'JM',
    alpha3: 'JAM',
    numeric: '388',
    currencyAlphabeticCode: 'JMD',
    currencyCountryName: 'JAMAICA',
    currencyMinorUnit: '2',
    currencyName: 'Jamaican Dollar',
    currencyNumericCode: '388'
  },
  {
    name: 'Japan',
    alpha2: 'JP',
    alpha3: 'JPN',
    numeric: '392',
    currencyAlphabeticCode: 'JPY',
    currencyCountryName: 'JAPAN',
    currencyMinorUnit: '0',
    currencyName: 'Yen',
    currencyNumericCode: '392'
  },
  {
    name: 'Jersey',
    alpha2: 'JE',
    alpha3: 'JEY',
    numeric: '832',
    currencyAlphabeticCode: 'GBP',
    currencyCountryName: 'JERSEY',
    currencyMinorUnit: '2',
    currencyName: 'Pound Sterling',
    currencyNumericCode: '826'
  },
  {
    name: 'Jordan',
    alpha2: 'JO',
    alpha3: 'JOR',
    numeric: '400',
    currencyAlphabeticCode: 'JOD',
    currencyCountryName: 'JORDAN',
    currencyMinorUnit: '3',
    currencyName: 'Jordanian Dinar',
    currencyNumericCode: '400'
  },
  {
    name: 'Kazakhstan',
    alpha2: 'KZ',
    alpha3: 'KAZ',
    numeric: '398',
    currencyAlphabeticCode: 'KZT',
    currencyCountryName: 'KAZAKHSTAN',
    currencyMinorUnit: '2',
    currencyName: 'Tenge',
    currencyNumericCode: '398'
  },
  {
    name: 'Kenya',
    alpha2: 'KE',
    alpha3: 'KEN',
    numeric: '404',
    currencyAlphabeticCode: 'KES',
    currencyCountryName: 'KENYA',
    currencyMinorUnit: '2',
    currencyName: 'Kenyan Shilling',
    currencyNumericCode: '404'
  },
  {
    name: 'Kiribati',
    alpha2: 'KI',
    alpha3: 'KIR',
    numeric: '296',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'KIRIBATI',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Kuwait',
    alpha2: 'KW',
    alpha3: 'KWT',
    numeric: '414',
    currencyAlphabeticCode: 'KWD',
    currencyCountryName: 'KUWAIT',
    currencyMinorUnit: '3',
    currencyName: 'Kuwaiti Dinar',
    currencyNumericCode: '414'
  },
  {
    name: 'Kyrgyzstan',
    alpha2: 'KG',
    alpha3: 'KGZ',
    numeric: '417',
    currencyAlphabeticCode: 'KGS',
    currencyCountryName: 'KYRGYZSTAN',
    currencyMinorUnit: '2',
    currencyName: 'Som',
    currencyNumericCode: '417'
  },
  {
    name: 'Laos',
    alpha2: 'LA',
    alpha3: 'LAO',
    numeric: '418',
    currencyAlphabeticCode: 'LAK',
    currencyCountryName: 'LAO PEOPLE\u2019S DEMOCRATIC REPUBLIC',
    currencyMinorUnit: '2',
    currencyName: 'Lao Kip',
    currencyNumericCode: '418'
  },
  {
    name: 'Latvia',
    alpha2: 'LV',
    alpha3: 'LVA',
    numeric: '428',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'LATVIA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Lebanon',
    alpha2: 'LB',
    alpha3: 'LBN',
    numeric: '422',
    currencyAlphabeticCode: 'LBP',
    currencyCountryName: 'LEBANON',
    currencyMinorUnit: '2',
    currencyName: 'Lebanese Pound',
    currencyNumericCode: '422'
  },
  {
    name: 'Lesotho',
    alpha2: 'LS',
    alpha3: 'LSO',
    numeric: '426',
    currencyAlphabeticCode: 'LSL,ZAR',
    currencyCountryName: 'LESOTHO',
    currencyMinorUnit: '2,2',
    currencyName: 'Loti,Rand',
    currencyNumericCode: '426,710'
  },
  {
    name: 'Liberia',
    alpha2: 'LR',
    alpha3: 'LBR',
    numeric: '430',
    currencyAlphabeticCode: 'LRD',
    currencyCountryName: 'LIBERIA',
    currencyMinorUnit: '2',
    currencyName: 'Liberian Dollar',
    currencyNumericCode: '430'
  },
  {
    name: 'Libya',
    alpha2: 'LY',
    alpha3: 'LBY',
    numeric: '434',
    currencyAlphabeticCode: 'LYD',
    currencyCountryName: 'LIBYA',
    currencyMinorUnit: '3',
    currencyName: 'Libyan Dinar',
    currencyNumericCode: '434'
  },
  {
    name: 'Liechtenstein',
    alpha2: 'LI',
    alpha3: 'LIE',
    numeric: '438',
    currencyAlphabeticCode: 'CHF',
    currencyCountryName: 'LIECHTENSTEIN',
    currencyMinorUnit: '2',
    currencyName: 'Swiss Franc',
    currencyNumericCode: '756'
  },
  {
    name: 'Lithuania',
    alpha2: 'LT',
    alpha3: 'LTU',
    numeric: '440',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'LITHUANIA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Luxembourg',
    alpha2: 'LU',
    alpha3: 'LUX',
    numeric: '442',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'LUXEMBOURG',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Madagascar',
    alpha2: 'MG',
    alpha3: 'MDG',
    numeric: '450',
    currencyAlphabeticCode: 'MGA',
    currencyCountryName: 'MADAGASCAR',
    currencyMinorUnit: '2',
    currencyName: 'Malagasy Ariary',
    currencyNumericCode: '969'
  },
  {
    name: 'Malawi',
    alpha2: 'MW',
    alpha3: 'MWI',
    numeric: '454',
    currencyAlphabeticCode: 'MWK',
    currencyCountryName: 'MALAWI',
    currencyMinorUnit: '2',
    currencyName: 'Malawi Kwacha',
    currencyNumericCode: '454'
  },
  {
    name: 'Malaysia',
    alpha2: 'MY',
    alpha3: 'MYS',
    numeric: '458',
    currencyAlphabeticCode: 'MYR',
    currencyCountryName: 'MALAYSIA',
    currencyMinorUnit: '2',
    currencyName: 'Malaysian Ringgit',
    currencyNumericCode: '458'
  },
  {
    name: 'Maldives',
    alpha2: 'MV',
    alpha3: 'MDV',
    numeric: '462',
    currencyAlphabeticCode: 'MVR',
    currencyCountryName: 'MALDIVES',
    currencyMinorUnit: '2',
    currencyName: 'Rufiyaa',
    currencyNumericCode: '462'
  },
  {
    name: 'Mali',
    alpha2: 'ML',
    alpha3: 'MLI',
    numeric: '466',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: 'MALI',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'Malta',
    alpha2: 'MT',
    alpha3: 'MLT',
    numeric: '470',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'MALTA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Marshall Islands',
    alpha2: 'MH',
    alpha3: 'MHL',
    numeric: '584',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'MARSHALL ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Martinique',
    alpha2: 'MQ',
    alpha3: 'MTQ',
    numeric: '474',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'MARTINIQUE',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Mauritania',
    alpha2: 'MR',
    alpha3: 'MRT',
    numeric: '478',
    currencyAlphabeticCode: 'MRO',
    currencyCountryName: 'MAURITANIA',
    currencyMinorUnit: '2',
    currencyName: 'Ouguiya',
    currencyNumericCode: '478'
  },
  {
    name: 'Mauritius',
    alpha2: 'MU',
    alpha3: 'MUS',
    numeric: '480',
    currencyAlphabeticCode: 'MUR',
    currencyCountryName: 'MAURITIUS',
    currencyMinorUnit: '2',
    currencyName: 'Mauritius Rupee',
    currencyNumericCode: '480'
  },
  {
    name: 'Mayotte',
    alpha2: 'YT',
    alpha3: 'MYT',
    numeric: '175',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'MAYOTTE',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Mexico',
    alpha2: 'MX',
    alpha3: 'MEX',
    numeric: '484',
    currencyAlphabeticCode: 'MXN',
    currencyCountryName: 'MEXICO',
    currencyMinorUnit: '2',
    currencyName: 'Mexican Peso',
    currencyNumericCode: '484'
  },
  {
    name: 'Micronesia',
    alpha2: 'FM',
    alpha3: 'FSM',
    numeric: '583',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'MICRONESIA (FEDERATED STATES OF)',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Monaco',
    alpha2: 'MC',
    alpha3: 'MCO',
    numeric: '492',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'MONACO',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Mongolia',
    alpha2: 'MN',
    alpha3: 'MNG',
    numeric: '496',
    currencyAlphabeticCode: 'MNT',
    currencyCountryName: 'MONGOLIA',
    currencyMinorUnit: '2',
    currencyName: 'Tugrik',
    currencyNumericCode: '496'
  },
  {
    name: 'Montenegro',
    alpha2: 'ME',
    alpha3: 'MNE',
    numeric: '499',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'MONTENEGRO',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Montserrat',
    alpha2: 'MS',
    alpha3: 'MSR',
    numeric: '500',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'MONTSERRAT',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'Morocco',
    alpha2: 'MA',
    alpha3: 'MAR',
    numeric: '504',
    currencyAlphabeticCode: 'MAD',
    currencyCountryName: 'MOROCCO',
    currencyMinorUnit: '2',
    currencyName: 'Moroccan Dirham',
    currencyNumericCode: '504'
  },
  {
    name: 'Mozambique',
    alpha2: 'MZ',
    alpha3: 'MOZ',
    numeric: '508',
    currencyAlphabeticCode: 'MZN',
    currencyCountryName: 'MOZAMBIQUE',
    currencyMinorUnit: '2',
    currencyName: 'Mozambique Metical',
    currencyNumericCode: '943'
  },
  {
    name: 'Myanmar',
    alpha2: 'MM',
    alpha3: 'MMR',
    numeric: '104',
    currencyAlphabeticCode: 'MMK',
    currencyCountryName: 'MYANMAR',
    currencyMinorUnit: '2',
    currencyName: 'Kyat',
    currencyNumericCode: '104'
  },
  {
    name: 'Namibia',
    alpha2: 'NA',
    alpha3: 'NAM',
    numeric: '516',
    currencyAlphabeticCode: 'NAD,ZAR',
    currencyCountryName: 'NAMIBIA',
    currencyMinorUnit: '2,2',
    currencyName: 'Namibia Dollar,Rand',
    currencyNumericCode: '516,710'
  },
  {
    name: 'Nauru',
    alpha2: 'NR',
    alpha3: 'NRU',
    numeric: '520',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'NAURU',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Nepal',
    alpha2: 'NP',
    alpha3: 'NPL',
    numeric: '524',
    currencyAlphabeticCode: 'NPR',
    currencyCountryName: 'NEPAL',
    currencyMinorUnit: '2',
    currencyName: 'Nepalese Rupee',
    currencyNumericCode: '524'
  },
  {
    name: 'Netherlands',
    alpha2: 'NL',
    alpha3: 'NLD',
    numeric: '528',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'NETHERLANDS',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'New Caledonia',
    alpha2: 'NC',
    alpha3: 'NCL',
    numeric: '540',
    currencyAlphabeticCode: 'XPF',
    currencyCountryName: 'NEW CALEDONIA',
    currencyMinorUnit: '0',
    currencyName: 'CFP Franc',
    currencyNumericCode: '953'
  },
  {
    name: 'New Zealand',
    alpha2: 'NZ',
    alpha3: 'NZL',
    numeric: '554',
    currencyAlphabeticCode: 'NZD',
    currencyCountryName: 'NEW ZEALAND',
    currencyMinorUnit: '2',
    currencyName: 'New Zealand Dollar',
    currencyNumericCode: '554'
  },
  {
    name: 'Nicaragua',
    alpha2: 'NI',
    alpha3: 'NIC',
    numeric: '558',
    currencyAlphabeticCode: 'NIO',
    currencyCountryName: 'NICARAGUA',
    currencyMinorUnit: '2',
    currencyName: 'Cordoba Oro',
    currencyNumericCode: '558'
  },
  {
    name: 'Niger',
    alpha2: 'NE',
    alpha3: 'NER',
    numeric: '562',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: 'NIGER',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'Nigeria',
    alpha2: 'NG',
    alpha3: 'NGA',
    numeric: '566',
    currencyAlphabeticCode: 'NGN',
    currencyCountryName: 'NIGERIA',
    currencyMinorUnit: '2',
    currencyName: 'Naira',
    currencyNumericCode: '566'
  },
  {
    name: 'Niue',
    alpha2: 'NU',
    alpha3: 'NIU',
    numeric: '570',
    currencyAlphabeticCode: 'NZD',
    currencyCountryName: 'NIUE',
    currencyMinorUnit: '2',
    currencyName: 'New Zealand Dollar',
    currencyNumericCode: '554'
  },
  {
    name: 'Norfolk Island',
    alpha2: 'NF',
    alpha3: 'NFK',
    numeric: '574',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'NORFOLK ISLAND',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Northern Mariana Islands',
    alpha2: 'MP',
    alpha3: 'MNP',
    numeric: '580',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'NORTHERN MARIANA ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Norway',
    alpha2: 'NO',
    alpha3: 'NOR',
    numeric: '578',
    currencyAlphabeticCode: 'NOK',
    currencyCountryName: 'NORWAY',
    currencyMinorUnit: '2',
    currencyName: 'Norwegian Krone',
    currencyNumericCode: '578'
  },
  {
    name: 'Oman',
    alpha2: 'OM',
    alpha3: 'OMN',
    numeric: '512',
    currencyAlphabeticCode: 'OMR',
    currencyCountryName: 'OMAN',
    currencyMinorUnit: '3',
    currencyName: 'Rial Omani',
    currencyNumericCode: '512'
  },
  {
    name: 'Pakistan',
    alpha2: 'PK',
    alpha3: 'PAK',
    numeric: '586',
    currencyAlphabeticCode: 'PKR',
    currencyCountryName: 'PAKISTAN',
    currencyMinorUnit: '2',
    currencyName: 'Pakistan Rupee',
    currencyNumericCode: '586'
  },
  {
    name: 'Palau',
    alpha2: 'PW',
    alpha3: 'PLW',
    numeric: '585',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'PALAU',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Panama',
    alpha2: 'PA',
    alpha3: 'PAN',
    numeric: '591',
    currencyAlphabeticCode: 'PAB,USD',
    currencyCountryName: 'PANAMA',
    currencyMinorUnit: '2,2',
    currencyName: 'Balboa,US Dollar',
    currencyNumericCode: '5,840'
  },
  {
    name: 'Papua New Guinea',
    alpha2: 'PG',
    alpha3: 'PNG',
    numeric: '598',
    currencyAlphabeticCode: 'PGK',
    currencyCountryName: 'PAPUA NEW GUINEA',
    currencyMinorUnit: '2',
    currencyName: 'Kina',
    currencyNumericCode: '598'
  },
  {
    name: 'Paraguay',
    alpha2: 'PY',
    alpha3: 'PRY',
    numeric: '600',
    currencyAlphabeticCode: 'PYG',
    currencyCountryName: 'PARAGUAY',
    currencyMinorUnit: '0',
    currencyName: 'Guarani',
    currencyNumericCode: '600'
  },
  {
    name: 'Peru',
    alpha2: 'PE',
    alpha3: 'PER',
    numeric: '604',
    currencyAlphabeticCode: 'PEN',
    currencyCountryName: 'PERU',
    currencyMinorUnit: '2',
    currencyName: 'Sol',
    currencyNumericCode: '604'
  },
  {
    name: 'Philippines',
    alpha2: 'PH',
    alpha3: 'PHL',
    numeric: '608',
    currencyAlphabeticCode: 'PHP',
    currencyCountryName: 'PHILIPPINES',
    currencyMinorUnit: '2',
    currencyName: 'Philippine Piso',
    currencyNumericCode: '608'
  },
  {
    name: 'Pitcairn Islands',
    alpha2: 'PN',
    alpha3: 'PCN',
    numeric: '612',
    currencyAlphabeticCode: 'NZD',
    currencyCountryName: 'PITCAIRN',
    currencyMinorUnit: '2',
    currencyName: 'New Zealand Dollar',
    currencyNumericCode: '554'
  },
  {
    name: 'Poland',
    alpha2: 'PL',
    alpha3: 'POL',
    numeric: '616',
    currencyAlphabeticCode: 'PLN',
    currencyCountryName: 'POLAND',
    currencyMinorUnit: '2',
    currencyName: 'Zloty',
    currencyNumericCode: '985'
  },
  {
    name: 'Portugal',
    alpha2: 'PT',
    alpha3: 'PRT',
    numeric: '620',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'PORTUGAL',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Puerto Rico',
    alpha2: 'PR',
    alpha3: 'PRI',
    numeric: '630',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'PUERTO RICO',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Qatar',
    alpha2: 'QA',
    alpha3: 'QAT',
    numeric: '634',
    currencyAlphabeticCode: 'QAR',
    currencyCountryName: 'QATAR',
    currencyMinorUnit: '2',
    currencyName: 'Qatari Rial',
    currencyNumericCode: '634'
  },
  {
    name: 'South Korea',
    alpha2: 'KR',
    alpha3: 'KOR',
    numeric: '410',
    currencyAlphabeticCode: 'KRW',
    currencyCountryName: 'KOREA (THE REPUBLIC OF)',
    currencyMinorUnit: '0',
    currencyName: 'Won',
    currencyNumericCode: '410'
  },
  {
    name: 'Moldova',
    alpha2: 'MD',
    alpha3: 'MDA',
    numeric: '498',
    currencyAlphabeticCode: 'MDL',
    currencyCountryName: 'MOLDOVA (THE REPUBLIC OF)',
    currencyMinorUnit: '2',
    currencyName: 'Moldovan Leu',
    currencyNumericCode: '498'
  },
  {
    name: 'Romania',
    alpha2: 'RO',
    alpha3: 'ROU',
    numeric: '642',
    currencyAlphabeticCode: 'RON',
    currencyCountryName: 'ROMANIA',
    currencyMinorUnit: '2',
    currencyName: 'Romanian Leu',
    currencyNumericCode: '946'
  },
  {
    name: 'Russia',
    alpha2: 'RU',
    alpha3: 'RUS',
    numeric: '643',
    currencyAlphabeticCode: 'RUB',
    currencyCountryName: 'RUSSIAN FEDERATION',
    currencyMinorUnit: '2',
    currencyName: 'Russian Ruble',
    currencyNumericCode: '643'
  },
  {
    name: 'Rwanda',
    alpha2: 'RW',
    alpha3: 'RWA',
    numeric: '646',
    currencyAlphabeticCode: 'RWF',
    currencyCountryName: 'RWANDA',
    currencyMinorUnit: '0',
    currencyName: 'Rwanda Franc',
    currencyNumericCode: '646'
  },
  {
    name: 'R\u00e9union',
    alpha2: 'RE',
    alpha3: 'REU',
    numeric: '638',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'R\u00c9UNION',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'St. Barth\u00e9lemy',
    alpha2: 'BL',
    alpha3: 'BLM',
    numeric: '652',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'SAINT BARTH\u00c9LEMY',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'St. Helena',
    alpha2: 'SH',
    alpha3: 'SHN',
    numeric: '654',
    currencyAlphabeticCode: 'SHP',
    currencyCountryName: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    currencyMinorUnit: '2',
    currencyName: 'Saint Helena Pound',
    currencyNumericCode: '654'
  },
  {
    name: 'St. Kitts & Nevis',
    alpha2: 'KN',
    alpha3: 'KNA',
    numeric: '659',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'SAINT KITTS AND NEVIS',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'St. Lucia',
    alpha2: 'LC',
    alpha3: 'LCA',
    numeric: '662',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'SAINT LUCIA',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'St. Martin',
    alpha2: 'MF',
    alpha3: 'MAF',
    numeric: '663',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'SAINT MARTIN (FRENCH PART)',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'St. Pierre & Miquelon',
    alpha2: 'PM',
    alpha3: 'SPM',
    numeric: '666',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'SAINT PIERRE AND MIQUELON',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'St. Vincent & Grenadines',
    alpha2: 'VC',
    alpha3: 'VCT',
    numeric: '670',
    currencyAlphabeticCode: 'XCD',
    currencyCountryName: 'SAINT VINCENT AND THE GRENADINES',
    currencyMinorUnit: '2',
    currencyName: 'East Caribbean Dollar',
    currencyNumericCode: '951'
  },
  {
    name: 'Samoa',
    alpha2: 'WS',
    alpha3: 'WSM',
    numeric: '882',
    currencyAlphabeticCode: 'WST',
    currencyCountryName: 'SAMOA',
    currencyMinorUnit: '2',
    currencyName: 'Tala',
    currencyNumericCode: '882'
  },
  {
    name: 'San Marino',
    alpha2: 'SM',
    alpha3: 'SMR',
    numeric: '674',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'SAN MARINO',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'S\u00e3o Tom\u00e9 & Pr\u00edncipe',
    alpha2: 'ST',
    alpha3: 'STP',
    numeric: '678',
    currencyAlphabeticCode: 'STD',
    currencyCountryName: 'SAO TOME AND PRINCIPE',
    currencyMinorUnit: '2',
    currencyName: 'Dobra',
    currencyNumericCode: '678'
  },
  // {
  // },
  {
    name: 'Saudi Arabia',
    alpha2: 'SA',
    alpha3: 'SAU',
    numeric: '682',
    currencyAlphabeticCode: 'SAR',
    currencyCountryName: 'SAUDI ARABIA',
    currencyMinorUnit: '2',
    currencyName: 'Saudi Riyal',
    currencyNumericCode: '682'
  },
  {
    name: 'Senegal',
    alpha2: 'SN',
    alpha3: 'SEN',
    numeric: '686',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: 'SENEGAL',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'Serbia',
    alpha2: 'RS',
    alpha3: 'SRB',
    numeric: '688',
    currencyAlphabeticCode: 'RSD',
    currencyCountryName: 'SERBIA',
    currencyMinorUnit: '2',
    currencyName: 'Serbian Dinar',
    currencyNumericCode: '941'
  },
  {
    name: 'Seychelles',
    alpha2: 'SC',
    alpha3: 'SYC',
    numeric: '690',
    currencyAlphabeticCode: 'SCR',
    currencyCountryName: 'SEYCHELLES',
    currencyMinorUnit: '2',
    currencyName: 'Seychelles Rupee',
    currencyNumericCode: '690'
  },
  {
    name: 'Sierra Leone',
    alpha2: 'SL',
    alpha3: 'SLE',
    numeric: '694',
    currencyAlphabeticCode: 'SLL',
    currencyCountryName: 'SIERRA LEONE',
    currencyMinorUnit: '2',
    currencyName: 'Leone',
    currencyNumericCode: '694'
  },
  {
    name: 'Singapore',
    alpha2: 'SG',
    alpha3: 'SGP',
    numeric: '702',
    currencyAlphabeticCode: 'SGD',
    currencyCountryName: 'SINGAPORE',
    currencyMinorUnit: '2',
    currencyName: 'Singapore Dollar',
    currencyNumericCode: '702'
  },
  {
    name: 'Sint Maarten',
    alpha2: 'SX',
    alpha3: 'SXM',
    numeric: '534',
    currencyAlphabeticCode: 'ANG',
    currencyCountryName: 'SINT MAARTEN (DUTCH PART)',
    currencyMinorUnit: '2',
    currencyName: 'Netherlands Antillean Guilder',
    currencyNumericCode: '532'
  },
  {
    name: 'Slovakia',
    alpha2: 'SK',
    alpha3: 'SVK',
    numeric: '703',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'SLOVAKIA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Slovenia',
    alpha2: 'SI',
    alpha3: 'SVN',
    numeric: '705',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'SLOVENIA',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Solomon Islands',
    alpha2: 'SB',
    alpha3: 'SLB',
    numeric: '090',
    currencyAlphabeticCode: 'SBD',
    currencyCountryName: 'SOLOMON ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'Solomon Islands Dollar',
    currencyNumericCode: '090'
  },
  {
    name: 'Somalia',
    alpha2: 'SO',
    alpha3: 'SOM',
    numeric: '706',
    currencyAlphabeticCode: 'SOS',
    currencyCountryName: 'SOMALIA',
    currencyMinorUnit: '2',
    currencyName: 'Somali Shilling',
    currencyNumericCode: '706'
  },
  {
    name: 'South Africa',
    alpha2: 'ZA',
    alpha3: 'ZAF',
    numeric: '710',
    currencyAlphabeticCode: 'ZAR',
    currencyCountryName: 'SOUTH AFRICA',
    currencyMinorUnit: '2',
    currencyName: 'Rand',
    currencyNumericCode: '710'
  },
  {
    name: 'South Sudan',
    alpha2: 'SS',
    alpha3: 'SSD',
    numeric: '728',
    currencyAlphabeticCode: 'SSP',
    currencyCountryName: 'SOUTH SUDAN',
    currencyMinorUnit: '2',
    currencyName: 'South Sudanese Pound',
    currencyNumericCode: '728'
  },
  {
    name: 'Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    numeric: '724',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: 'SPAIN',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  },
  {
    name: 'Sri Lanka',
    alpha2: 'LK',
    alpha3: 'LKA',
    numeric: '144',
    currencyAlphabeticCode: 'LKR',
    currencyCountryName: 'SRI LANKA',
    currencyMinorUnit: '2',
    currencyName: 'Sri Lanka Rupee',
    currencyNumericCode: '144'
  },
  {
    name: 'Sudan',
    alpha2: 'SD',
    alpha3: 'SDN',
    numeric: '729',
    currencyAlphabeticCode: 'SDG',
    currencyCountryName: 'SUDAN',
    currencyMinorUnit: '2',
    currencyName: 'Sudanese Pound',
    currencyNumericCode: '938'
  },
  {
    name: 'Suriname',
    alpha2: 'SR',
    alpha3: 'SUR',
    numeric: '740',
    currencyAlphabeticCode: 'SRD',
    currencyCountryName: 'SURINAME',
    currencyMinorUnit: '2',
    currencyName: 'Surinam Dollar',
    currencyNumericCode: '968'
  },
  {
    name: 'Svalbard & Jan Mayen',
    alpha2: 'SJ',
    alpha3: 'SJM',
    numeric: '744',
    currencyAlphabeticCode: 'NOK',
    currencyCountryName: 'SVALBARD AND JAN MAYEN',
    currencyMinorUnit: '2',
    currencyName: 'Norwegian Krone',
    currencyNumericCode: '578'
  },
  {
    name: 'Swaziland',
    alpha2: 'SZ',
    alpha3: 'SWZ',
    numeric: '748',
    currencyAlphabeticCode: 'SZL',
    currencyCountryName: 'SWAZILAND',
    currencyMinorUnit: '2',
    currencyName: 'Lilangeni',
    currencyNumericCode: '748'
  },
  {
    name: 'Sweden',
    alpha2: 'SE',
    alpha3: 'SWE',
    numeric: '752',
    currencyAlphabeticCode: 'SEK',
    currencyCountryName: 'SWEDEN',
    currencyMinorUnit: '2',
    currencyName: 'Swedish Krona',
    currencyNumericCode: '752'
  },
  {
    name: 'Switzerland',
    alpha2: 'CH',
    alpha3: 'CHE',
    numeric: '756',
    currencyAlphabeticCode: 'CHF',
    currencyCountryName: 'SWITZERLAND',
    currencyMinorUnit: '2',
    currencyName: 'Swiss Franc',
    currencyNumericCode: '756'
  },
  {
    name: 'Syria',
    alpha2: 'SY',
    alpha3: 'SYR',
    numeric: '760',
    currencyAlphabeticCode: 'SYP',
    currencyCountryName: 'SYRIAN ARAB REPUBLIC',
    currencyMinorUnit: '2',
    currencyName: 'Syrian Pound',
    currencyNumericCode: '760'
  },
  {
    name: 'Tajikistan',
    alpha2: 'TJ',
    alpha3: 'TJK',
    numeric: '762',
    currencyAlphabeticCode: 'TJS',
    currencyCountryName: 'TAJIKISTAN',
    currencyMinorUnit: '2',
    currencyName: 'Somoni',
    currencyNumericCode: '972'
  },
  {
    name: 'Thailand',
    alpha2: 'TH',
    alpha3: 'THA',
    numeric: '764',
    currencyAlphabeticCode: 'THB',
    currencyCountryName: 'THAILAND',
    currencyMinorUnit: '2',
    currencyName: 'Baht',
    currencyNumericCode: '764'
  },
  {
    name: 'Macedonia',
    alpha2: 'MK',
    alpha3: 'MKD',
    numeric: '807',
    currencyAlphabeticCode: 'MKD',
    currencyCountryName: 'MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)',
    currencyMinorUnit: '2',
    currencyName: 'Denar',
    currencyNumericCode: '807'
  },
  {
    name: 'Timor-Leste',
    alpha2: 'TL',
    alpha3: 'TLS',
    numeric: '626',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'TIMOR-LESTE',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Togo',
    alpha2: 'TG',
    alpha3: 'TGO',
    numeric: '768',
    currencyAlphabeticCode: 'XOF',
    currencyCountryName: 'TOGO',
    currencyMinorUnit: '0',
    currencyName: 'CFA Franc BCEAO',
    currencyNumericCode: '952'
  },
  {
    name: 'Tokelau',
    alpha2: 'TK',
    alpha3: 'TKL',
    numeric: '772',
    currencyAlphabeticCode: 'NZD',
    currencyCountryName: 'TOKELAU',
    currencyMinorUnit: '2',
    currencyName: 'New Zealand Dollar',
    currencyNumericCode: '554'
  },
  {
    name: 'Tonga',
    alpha2: 'TO',
    alpha3: 'TON',
    numeric: '776',
    currencyAlphabeticCode: 'TOP',
    currencyCountryName: 'TONGA',
    currencyMinorUnit: '2',
    currencyName: 'Pa\u2019anga',
    currencyNumericCode: '776'
  },
  {
    name: 'Trinidad & Tobago',
    alpha2: 'TT',
    alpha3: 'TTO',
    numeric: '780',
    currencyAlphabeticCode: 'TTD',
    currencyCountryName: 'TRINIDAD AND TOBAGO',
    currencyMinorUnit: '2',
    currencyName: 'Trinidad and Tobago Dollar',
    currencyNumericCode: '780'
  },
  {
    name: 'Tunisia',
    alpha2: 'TN',
    alpha3: 'TUN',
    numeric: '788',
    currencyAlphabeticCode: 'TND',
    currencyCountryName: 'TUNISIA',
    currencyMinorUnit: '3',
    currencyName: 'Tunisian Dinar',
    currencyNumericCode: '788'
  },
  {
    name: 'Turkey',
    alpha2: 'TR',
    alpha3: 'TUR',
    numeric: '792',
    currencyAlphabeticCode: 'TRY',
    currencyCountryName: 'TURKEY',
    currencyMinorUnit: '2',
    currencyName: 'Turkish Lira',
    currencyNumericCode: '949'
  },
  {
    name: 'Turkmenistan',
    alpha2: 'TM',
    alpha3: 'TKM',
    numeric: '795',
    currencyAlphabeticCode: 'TMT',
    currencyCountryName: 'TURKMENISTAN',
    currencyMinorUnit: '2',
    currencyName: 'Turkmenistan New Manat',
    currencyNumericCode: '934'
  },
  {
    name: 'Turks & Caicos Islands',
    alpha2: 'TC',
    alpha3: 'TCA',
    numeric: '796',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'TURKS AND CAICOS ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Tuvalu',
    alpha2: 'TV',
    alpha3: 'TUV',
    numeric: '798',
    currencyAlphabeticCode: 'AUD',
    currencyCountryName: 'TUVALU',
    currencyMinorUnit: '2',
    currencyName: 'Australian Dollar',
    currencyNumericCode: '036'
  },
  {
    name: 'Uganda',
    alpha2: 'UG',
    alpha3: 'UGA',
    numeric: '800',
    currencyAlphabeticCode: 'UGX',
    currencyCountryName: 'UGANDA',
    currencyMinorUnit: '0',
    currencyName: 'Uganda Shilling',
    currencyNumericCode: '800'
  },
  {
    name: 'Ukraine',
    alpha2: 'UA',
    alpha3: 'UKR',
    numeric: '804',
    currencyAlphabeticCode: 'UAH',
    currencyCountryName: 'UKRAINE',
    currencyMinorUnit: '2',
    currencyName: 'Hryvnia',
    currencyNumericCode: '980'
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    numeric: '784',
    currencyAlphabeticCode: 'AED',
    currencyCountryName: 'UNITED ARAB EMIRATES',
    currencyMinorUnit: '2',
    currencyName: 'UAE Dirham',
    currencyNumericCode: '784'
  },
  {
    name: 'UK',
    alpha2: 'GB',
    alpha3: 'GBR',
    numeric: '826',
    currencyAlphabeticCode: 'GBP',
    currencyCountryName: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND',
    currencyMinorUnit: '2',
    currencyName: 'Pound Sterling',
    currencyNumericCode: '826'
  },
  {
    name: 'Tanzania',
    alpha2: 'TZ',
    alpha3: 'TZA',
    numeric: '834',
    currencyAlphabeticCode: 'TZS',
    currencyCountryName: 'TANZANIA, UNITED REPUBLIC OF',
    currencyMinorUnit: '2',
    currencyName: 'Tanzanian Shilling',
    currencyNumericCode: '834'
  },
  {
    name: 'U.S. Outlying Islands',
    alpha2: 'UM',
    alpha3: 'UMI',
    numeric: '581',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'UNITED STATES MINOR OUTLYING ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'U.S. Virgin Islands',
    alpha2: 'VI',
    alpha3: 'VIR',
    numeric: '850',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'VIRGIN ISLANDS (U.S.)',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'US',
    alpha2: 'US',
    alpha3: 'USA',
    numeric: '840',
    currencyAlphabeticCode: 'USD',
    currencyCountryName: 'UNITED STATES OF AMERICA',
    currencyMinorUnit: '2',
    currencyName: 'US Dollar',
    currencyNumericCode: '840'
  },
  {
    name: 'Uruguay',
    alpha2: 'UY',
    alpha3: 'URY',
    numeric: '858',
    currencyAlphabeticCode: 'UYU',
    currencyCountryName: 'URUGUAY',
    currencyMinorUnit: '2',
    currencyName: 'Peso Uruguayo',
    currencyNumericCode: '858'
  },
  {
    name: 'Uzbekistan',
    alpha2: 'UZ',
    alpha3: 'UZB',
    numeric: '860',
    currencyAlphabeticCode: 'UZS',
    currencyCountryName: 'UZBEKISTAN',
    currencyMinorUnit: '2',
    currencyName: 'Uzbekistan Sum',
    currencyNumericCode: '860'
  },
  {
    name: 'Vanuatu',
    alpha2: 'VU',
    alpha3: 'VUT',
    numeric: '548',
    currencyAlphabeticCode: 'VUV',
    currencyCountryName: 'VANUATU',
    currencyMinorUnit: '0',
    currencyName: 'Vatu',
    currencyNumericCode: '548'
  },
  {
    name: 'Venezuela',
    alpha2: 'VE',
    alpha3: 'VEN',
    numeric: '862',
    currencyAlphabeticCode: 'VEF',
    currencyCountryName: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    currencyMinorUnit: '2',
    currencyName: 'Bol\u00edvar',
    currencyNumericCode: '937'
  },
  {
    name: 'Vietnam',
    alpha2: 'VN',
    alpha3: 'VNM',
    numeric: '704',
    currencyAlphabeticCode: 'VND',
    currencyCountryName: 'VIET NAM',
    currencyMinorUnit: '0',
    currencyName: 'Dong',
    currencyNumericCode: '704'
  },
  {
    name: 'Wallis & Futuna',
    alpha2: 'WF',
    alpha3: 'WLF',
    numeric: '876',
    currencyAlphabeticCode: 'XPF',
    currencyCountryName: 'WALLIS AND FUTUNA',
    currencyMinorUnit: '0',
    currencyName: 'CFP Franc',
    currencyNumericCode: '953'
  },
  {
    name: 'Western Sahara',
    alpha2: 'EH',
    alpha3: 'ESH',
    numeric: '732',
    currencyAlphabeticCode: 'MAD',
    currencyCountryName: 'WESTERN SAHARA',
    currencyMinorUnit: '2',
    currencyName: 'Moroccan Dirham',
    currencyNumericCode: '504'
  },
  {
    name: 'Yemen',
    alpha2: 'YE',
    alpha3: 'YEM',
    numeric: '887',
    currencyAlphabeticCode: 'YER',
    currencyCountryName: 'YEMEN',
    currencyMinorUnit: '2',
    currencyName: 'Yemeni Rial',
    currencyNumericCode: '886'
  },
  {
    name: 'Zambia',
    alpha2: 'ZM',
    alpha3: 'ZMB',
    numeric: '894',
    currencyAlphabeticCode: 'ZMW',
    currencyCountryName: 'ZAMBIA',
    currencyMinorUnit: '2',
    currencyName: 'Zambian Kwacha',
    currencyNumericCode: '967'
  },
  {
    name: 'Zimbabwe',
    alpha2: 'ZW',
    alpha3: 'ZWE',
    numeric: '716',
    currencyAlphabeticCode: 'ZWL',
    currencyCountryName: 'ZIMBABWE',
    currencyMinorUnit: '2',
    currencyName: 'Zimbabwe Dollar',
    currencyNumericCode: '932'
  },
  {
    name: '\u00c5land Islands',
    alpha2: 'AX',
    alpha3: 'ALA',
    numeric: '248',
    currencyAlphabeticCode: 'EUR',
    currencyCountryName: '\u00c5LAND ISLANDS',
    currencyMinorUnit: '2',
    currencyName: 'Euro',
    currencyNumericCode: '978'
  }
];

export default countryDatabase;
