name: Publish Beta Package

on:
  pull_request:
    branches:
      - 'main'

jobs:
  publishBeta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
      - name: Run Test
        run: npm run ci:test
      - name: Publish Beta
        uses: checkdigit/github-actions/publish-beta@main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
